// export const sampleClasses = [
//     {
//       day: 'Monday',
//       startPeriod: 1,
//       endPeriod: 2,
//       name: 'Operating System',
//       teacher: 'N.T.Nghia',
//       classroom: 'ONLINE',
//       startTime: '08:00',
//       endTime: '10:30',
//       semester: 'Semester 1',
//     },
//     {
//       day: 'Tuesday',
//       startPeriod: 2,
//       endPeriod: 4,
//       name: 'Artificial Intelligence',
//       teacher: 'N.T.Nghia',
//       classroom: 'ONLINE',
//       startTime: '10:35',
//       endTime: '13:05',
//       semester: 'Semester 1',
//     },
//     {
//       day: 'Wednesday',
//       startPeriod: 3,
//       endPeriod: 4,
//       name: 'Software Engineering',
//       teacher: 'N.T.Nghia',
//       classroom: 'ONLINE',
//       startTime: '13:15',
//       endTime: '15:45',
//       semester: 'Semester 1',
//     },
//     // Add more classes here
//   ];
  
//   export const semesters = ['Semester 1', 'Semester 2'];
  


export const sampleClasses = [
  {
    day: 'Monday',
    startPeriod: 1,
    endPeriod: 2,
    name: 'Operating System',
    teacher: 'N.T.Nghia',
    classroom: 'ONLINE',
    startTime: '08:00',
    endTime: '10:30',
    semester: 'Semester 1',
  },
  {
    day: 'Tuesday',
    startPeriod: 2,
    endPeriod: 4,
    name: 'Artificial Intelligence',
    teacher: 'N.T.Nghia',
    classroom: 'ONLINE',
    startTime: '10:35',
    endTime: '13:05',
    semester: 'Semester 1',
  },
  {
    day: 'Wednesday',
    startPeriod: 3,
    endPeriod: 4,
    name: 'Software Engineering',
    teacher: 'N.T.Nghia',
    classroom: 'ONLINE',
    startTime: '13:15',
    endTime: '15:45',
    semester: 'Semester 1',
  },
  // Add more classes here

  {
    day: 'Wednesday',
    stratPeriod: '11',
    endPeriod: '12',
    name: 'Probability, Statistic & Random Process	',
    teacher: 'Nguyen Van I',
    classroom: 'A2.402',
    startTime: '16:40',
    endTime: '18:20',
    semester: 'semester 1',
  },
  {
    day: 'Monday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'Digital Logic Design',
    teacher: 'Nguyen Van F',
    classroom: 'A2.213',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 2',
  },
  {
    day: 'Sunday',
    stratPeriod: '10',
    endPeriod: '12',
    name: 'Development and Operations',
    teacher: 'Nguyen Van U',
    classroom: 'A2.306',
    startTime: '15:50',
    endTime: '18:20',
    semester: 'semester 1',
  },
  {
    day: 'Thusday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'Digital Image Processing',
    teacher: 'Nguyen Van C',
    classroom: 'A2.107',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 2',
  },
  {
    day: 'Monday',
    stratPeriod: '8',
    endPeriod: '9',
    name: 'Special Study of the Field',
    teacher: 'Nguyen Van Y',
    classroom: 'A2.309',
    startTime: '14:05',
    endTime: '15:45',
    semester: 'semester 1',
  },
  {
    day: 'Friday',
    stratPeriod: '8',
    endPeriod: '9',
    name: 'System & Network Administration	',
    teacher: 'Nguyen Van D',
    classroom: 'A2.308',
    startTime: '14:05',
    endTime: '15:45',
    semester: 'semester 1',
  },
  {
    day: 'Wednesday',
    stratPeriod: '3',
    endPeriod: '4',
    name: 'Software Engineering',
    teacher: 'Nguyen Van X',
    classroom: 'A1.406',
    startTime: '09:40',
    endTime: '11:25',
    semester: 'semester 2',
  },
  {
    day: 'Sunday',
    stratPeriod: '11',
    endPeriod: '12',
    name: 'System and Network Security	',
    teacher: 'Nguyen Van T',
    classroom: 'A1.408',
    startTime: '16:40',
    endTime: '18:20',
    semester: 'semester 1',
  },
  {
    day: 'Tuesday',
    stratPeriod: '11',
    endPeriod: '12',
    name: 'Entrepreneurship	',
    teacher: 'Nguyen Van G',
    classroom: 'A2.105',
    startTime: '16:40',
    endTime: '18:20',
    semester: 'semester 2',
  },
  {
    day: 'Tuesday',
    stratPeriod: '3',
    endPeriod: '4',
    name: 'Mobile Application Development',
    teacher: 'Nguyen Van S',
    classroom: 'A1.305',
    startTime: '09:40',
    endTime: '11:25',
    semester: 'semester 2',
  },
  {
    day: 'Sunday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'Probability, Statistic & Random Process	',
    teacher: 'Nguyen Van J',
    classroom: 'A2.209',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 2',
  },
  {
    day: 'Monday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'IT Project Management',
    teacher: 'Nguyen Van S',
    classroom: 'A2.109',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 1',
  },
  {
    day: 'Tuesday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'History of Vietnamese Communist Party',
    teacher: 'Nguyen Van E',
    classroom: 'A1.407',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 2',
  },
  {
    day: 'Sunday',
    stratPeriod: '10',
    endPeriod: '11',
    name: 'Development and Operations',
    teacher: 'Nguyen Van G',
    classroom: 'A2.213',
    startTime: '15:50',
    endTime: '17:30',
    semester: 'semester 1',
  },
  {
    day: 'Tuesday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'History of Vietnamese Communist Party',
    teacher: 'Nguyen Van S',
    classroom: 'A1.101',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 1',
  },
  {
    day: 'Friday',
    stratPeriod: '11',
    endPeriod: '12',
    name: 'Mobile Application Development',
    teacher: 'Nguyen Van L',
    classroom: 'A1.308',
    startTime: '16:40',
    endTime: '18:20',
    semester: 'semester 2',
  },
  {
    day: 'Tuesday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'Internship',
    teacher: 'Nguyen Van J',
    classroom: 'A1.307',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 1',
  },
  {
    day: 'Monday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'Ho Chi Minh\'s Thoughts',
    teacher: 'Nguyen Van A',
    classroom: 'A2.409',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 2',
  },
  {
    day: 'Thusday',
    stratPeriod: '1',
    endPeriod: '4',
    name: 'Object-Oriented Programming',
    teacher: 'Nguyen Van Y',
    classroom: 'A1.312',
    startTime: '08:00',
    endTime: '11:25',
    semester: 'semester 1',
  },
  {
    day: 'Thusday',
    stratPeriod: '9',
    endPeriod: '10',
    name: 'Thesis',
    teacher: 'Nguyen Van C',
    classroom: 'A2.403',
    startTime: '14:55',
    endTime: '16:40',
    semester: 'semester 1',
  },
  {
    day: 'Sunday',
    stratPeriod: '8',
    endPeriod: '9',
    name: 'Internship',
    teacher: 'Nguyen Van P',
    classroom: 'online',
    startTime: '14:05',
    endTime: '15:45',
    semester: 'semester 2',
  },
  {
    day: 'Tuesday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'IT Project Management',
    teacher: 'Nguyen Van A',
    classroom: 'A2.304',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 1',
  },
  {
    day: 'Tuesday',
    stratPeriod: '5',
    endPeriod: '8',
    name: 'Object-Oriented Programming',
    teacher: 'Nguyen Van U',
    classroom: 'A2.112',
    startTime: '11:25',
    endTime: '14:55',
    semester: 'semester 1',
  },
  {
    day: 'Wednesday',
    stratPeriod: '7',
    endPeriod: '8',
    name: 'Listening AE1',
    teacher: 'Nguyen Van H',
    classroom: 'A1.112',
    startTime: '13:15',
    endTime: '14:55',
    semester: 'semester 1',
  },
  {
    day: 'Monday',
    stratPeriod: '8',
    endPeriod: '9',
    name: 'System & Network Administration	',
    teacher: 'Nguyen Van O',
    classroom: 'A1.113',
    startTime: '14:05',
    endTime: '15:45',
    semester: 'semester 1',
  },
  {
    day: 'Wednesday',
    stratPeriod: '1',
    endPeriod: '3',
    name: 'Listening AE1',
    teacher: 'Nguyen Van C',
    classroom: 'A1.103',
    startTime: '08:00',
    endTime: '10:30',
    semester: 'semester 1',
  },
  {
    day: 'Wednesday',
    stratPeriod: '3',
    endPeriod: '4',
    name: 'C/C++ Programming',
    teacher: 'Nguyen Van Y',
    classroom: 'A1.408',
    startTime: '09:40',
    endTime: '11:25',
    semester: 'semester 2',
  },
  {
    day: 'Friday',
    stratPeriod: '1',
    endPeriod: '2',
    name: 'Algorithms & Data Structures',
    teacher: 'Nguyen Van D',
    classroom: 'A1.109',
    startTime: '08:00',
    endTime: '09:40',
    semester: 'semester 1',
  },
  {
    day: 'Friday',
    stratPeriod: '11',
    endPeriod: '12',
    name: 'Special Study of the Field',
    teacher: 'Nguyen Van H',
    classroom: 'A2.103',
    startTime: '16:40',
    endTime: '18:20',
    semester: 'semester 1',
  },
  {
    day: 'Sunday',
    stratPeriod: '1',
    endPeriod: '4',
    name: 'Software Engineering',
    teacher: 'Nguyen Van Q',
    classroom: 'A2.309',
    startTime: '08:00',
    endTime: '11:25',
    semester: 'semester 1',
  },
  {
    day: 'Tuesday',
    stratPeriod: '4',
    endPeriod: '5',
    name: 'IT Project Management',
    teacher: 'Nguyen Van B',
    classroom: 'A1.110',
    startTime: '10:35',
    endTime: '12:15',
    semester: 'semester 2',
  },
];

export const semesters = ['Semester 1', 'Semester 2'];
